# Generated by Django 4.0.3 on 2022-07-27 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_topic_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='draft',
            field=models.BooleanField(default=False),
        ),
    ]
