# Generated by Django 4.0.3 on 2022-07-28 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='user',
        ),
    ]
