# Generated by Django 4.0.3 on 2022-07-28 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_remove_book_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='title',
        ),
        migrations.AddField(
            model_name='book',
            name='require',
            field=models.CharField(default='no', max_length=200),
        ),
    ]
